name: adalightclient
description: An adalightserver client
dependencies:
    polymer: ">=0.11.0 <0.12.0"
    paper_elements: ">=0.0.1 <0.1.0"
    color_picker: ">=1.1.4 <2.0.0"
transformers:
- polymer:
    entry_points: web/adalightclient.html
